// File generated by FlutterFire CLI.
// Run `flutterfire configure` to generate this file.
// 
// This file contains Firebase configuration for different platforms.
// 
// To generate this file:
// 1. Install FlutterFire CLI: `dart pub global activate flutterfire_cli`
// 2. Run: `flutterfire configure`
// 3. Follow the prompts to select your Firebase project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOUL3UrQVIvWNxQpuJRo5RWnqGF7haDyc',
    appId: '1:6754233751:web:3417896a6dc738eca768d2',
    messagingSenderId: '6754233751',
    projectId: 'mobile-messenger-a8e3f',
    authDomain: 'mobile-messenger-a8e3f.firebaseapp.com',
    storageBucket: 'mobile-messenger-a8e3f.firebasestorage.app',
    measurementId: 'G-W3NVPNPC08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCiyvtBh6zgOUUW6JQXnQbIPflzldMhhQ',
    appId: '1:6754233751:android:fea52e5e42b7698fa768d2',
    messagingSenderId: '6754233751',
    projectId: 'mobile-messenger-a8e3f',
    storageBucket: 'mobile-messenger-a8e3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw96BPF6ZmsKeZPa0H2Ru8cOgS6auPj0w',
    appId: '1:6754233751:ios:bbab246861ec5360a768d2',
    messagingSenderId: '6754233751',
    projectId: 'mobile-messenger-a8e3f',
    storageBucket: 'mobile-messenger-a8e3f.firebasestorage.app',
    iosBundleId: 'com.messenger.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyFormacOS',
    appId: '1:000:macos:0000000000',
    messagingSenderId: '000000000000',
    projectId: 'messenger-dev',
    storageBucket: 'messenger-dev.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  // Linux uses web credentials — Firebase does not have a native Linux SDK.
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDOUL3UrQVIvWNxQpuJRo5RWnqGF7haDyc',
    appId: '1:6754233751:web:3417896a6dc738eca768d2',
    messagingSenderId: '6754233751',
    projectId: 'mobile-messenger-a8e3f',
    authDomain: 'mobile-messenger-a8e3f.firebaseapp.com',
    storageBucket: 'mobile-messenger-a8e3f.firebasestorage.app',
  );
}