// File generated by FlutterFire CLI.
// Run `flutterfire configure` to generate this file.
// 
// This file contains Firebase configuration for different platforms.
// 
// To generate this file:
// 1. Install FlutterFire CLI: `dart pub global activate flutterfire_cli`
// 2. Run: `flutterfire configure`
// 3. Follow the prompts to select your Firebase project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWebPlatform',
    appId: '1:000:web:000000000000',
    messagingSenderId: '000000000000',
    projectId: 'messenger-dev',
    authDomain: 'messenger-dev.firebaseapp.com',
    storageBucket: 'messenger-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForAndroid',
    appId: '1:000:android:0000000000',
    messagingSenderId: '000000000000',
    projectId: 'messenger-dev',
    storageBucket: 'messenger-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForiOS',
    appId: '1:000:ios:0000000000',
    messagingSenderId: '000000000000',
    projectId: 'messenger-dev',
    storageBucket: 'messenger-dev.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyFormacOS',
    appId: '1:000:macos:0000000000',
    messagingSenderId: '000000000000',
    projectId: 'messenger-dev',
    storageBucket: 'messenger-dev.appspot.com',
    iosBundleId: 'com.example.frontend',
  );
}
